version: '3'

services:
  website:
    build: .
    links:
      - db
    env_file:
      - '.env'
    ports:
      - '8000:5000'

  db:
    image: mysql:5.7
    ports:
      - "33000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: utilities_admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: utilities

